all: GUI dataMonitor demo elevator elevatorManager floor userInteraction
GUI:
	javac GUI/*.java
dataMonitor:
	javac dataMonitor/*.java
demo:
	javac demo/*.java
elevator:
	javac elevator/*.java
elevatorManager:
	javac elevatorManager/*.java
floor:
	javac floor/*.java
userInteraction:
	javac userInteraction/*.java
